### ISSUE TITLE
Error while trying to install sidekick (pip)

### ISSUE THREAD

**Issue by sconetto** [fabiommendes/sidekick#1]
Hey there @fabiommendes,

I'm using sidekick (with ox-parser) to build a service to compile equations of a created language, but in the last week I'm not being able to build the service because of an pip install error while executing `pip install sidekick==0.3.0` (for instance if I try to install the latest version, 0.5.1, I get the same error).

Console output:
```
pip install sidekick==0.5.1
Collecting sidekick==0.5.1
  Using cached https://files.pythonhosted.org/packages/36/c6/f6bdf0fc77e8749f0eb4d6302211489f8675640f6971a1b94ea6f286b7fb/sidekick-0.5.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "/tmp/pip-install-s5_r0xyd/sidekick/src/sidekick/__init__.py", line 5, in <module>
        import cytoolz as toolz
    ModuleNotFoundError: No module named 'cytoolz'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-s5_r0xyd/sidekick/setup.py", line 12, in <module>
        install_requires=['toolz']
      File "/home/sconetto/.virtualenvs/sinesp/lib/python3.7/site-packages/setuptools/__init__.py", line 145, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib64/python3.7/distutils/core.py", line 121, in setup
        dist.parse_config_files()
      File "/home/sconetto/.virtualenvs/sinesp/lib/python3.7/site-packages/setuptools/dist.py", line 698, in parse_config_files
        ignore_option_errors=ignore_option_errors)
      File "/home/sconetto/.virtualenvs/sinesp/lib/python3.7/site-packages/setuptools/config.py", line 120, in parse_configuration
        meta.parse()
      File "/home/sconetto/.virtualenvs/sinesp/lib/python3.7/site-packages/setuptools/config.py", line 425, in parse
        section_parser_method(section_options)
      File "/home/sconetto/.virtualenvs/sinesp/lib/python3.7/site-packages/setuptools/config.py", line 398, in parse_section
        self[name] = value
      File "/home/sconetto/.virtualenvs/sinesp/lib/python3.7/site-packages/setuptools/config.py", line 183, in __setitem__
        value = parser(value)
      File "/home/sconetto/.virtualenvs/sinesp/lib/python3.7/site-packages/setuptools/config.py", line 513, in _parse_version
        version = self._parse_attr(value, self.package_dir)
      File "/home/sconetto/.virtualenvs/sinesp/lib/python3.7/site-packages/setuptools/config.py", line 348, in _parse_attr
        module = import_module(module_name)
      File "/home/sconetto/.virtualenvs/sinesp/lib/python3.7/importlib/__init__.py", line 127, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
      File "<frozen importlib._bootstrap>", line 983, in _find_and_load
      File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
      File "<frozen importlib._bootstrap_external>", line 728, in exec_module
      File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
      File "/tmp/pip-install-s5_r0xyd/sidekick/src/sidekick/__init__.py", line 8, in <module>
        import toolz  # noqa: F401
    ModuleNotFoundError: No module named 'toolz'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-s5_r0xyd/sidekick/
```

My environment:
```
uname -a
Linux manjaro-ws 4.19.32-1-MANJARO #1 SMP PREEMPT Wed Mar 27 18:55:07 UTC 2019 x86_64 GNU/Linux
```

```
lsb_release -a
LSB Version:	n/a
Distributor ID:	ManjaroLinux
Description:	Manjaro Linux
Release:	18.0.4
Codename:	Illyria
```

```
python --version
Python 3.7.3
```

```
pip --version
pip 19.0.3
```

Can you help me out to solve this?

**Comment by sconetto** [comment]
Hey there @fabiommendes 

update: I managed to workaround the error by installing the newest cytoolz on my venv, but now when I run the tests I get the following error:

```bash
pytest 
=========================================================== test session starts ============================================================
platform linux -- Python 3.7.3, pytest-3.8.2, py-1.8.0, pluggy-0.9.0 -- /home/sconetto/.virtualenvs/compiler/bin/python
cachedir: .pytest_cache
rootdir: /home/sconetto/project/fn-composta, inifile: pytest.ini
plugins: cov-2.6.0
collected 0 items / 1 errors                                                                                                               

================================================================== ERRORS ==================================================================
________________________________________________ ERROR collecting compiler/test_handler.py _________________________________________________
ImportError while importing test module '/home/sconetto/project/fn-composta/compiler/test_handler.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
compiler/test_handler.py:2: in <module>
    from compiler.handler import (check_table, complex_tokens)
compiler/handler.py:1: in <module>
    import ox
../../.virtualenvs/compiler/lib/python3.7/site-packages/ox/__init__.py:1: in <module>
    from . import lexer
../../.virtualenvs/compiler/lib/python3.7/site-packages/ox/lexer/__init__.py:1: in <module>
    from .lexer import Lexer, Token
../../.virtualenvs/compiler/lib/python3.7/site-packages/ox/lexer/lexer.py:5: in <module>
    from sidekick import Record, field, record
E   ImportError: cannot import name 'field' from 'sidekick' (/home/sconetto/.virtualenvs/compiler/lib/python3.7/site-packages/sidekick/__init__.py)
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 1 errors during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
========================================================= 1 error in 0.26 seconds ==========================================================
```

any ideas?

**Comment by sconetto** [comment]
Got the error.

The `ox-parser` (that is in the 0.2.4) is only compatible with `sidekick` 0.3.0.

So I guess the problem is the ox-parser. Any ETA on updates in that lib?

**Comment by fabiommendes** [comment]
It should indeed fix the version for sidekick as 0.3.0. I tried to update here, but it is failing the test suite possibly because of some incompatibility with Python 3.7. I will go back working on Ox as soon as sidekick stabilizes, but for now I do not have time to address this issue. In the mean time you might either fix the version or try another parsing lib for Python. The next version of ox will probably drop support for PLY and instead use [Lark](https://github.com/lark-parser/lark), which is much better IMHO.

**Comment by fabiommendes** [comment]
I reopened the issue in ox's repo. See: https://github.com/fabiommendes/ox/issues/1

**Comment by sconetto** [comment]
@fabiommendes Okay, I'll keep the conversation on the ox's repo. I will probably take a look in the next few weeks to try to help. Thank you for your answer!
